services:
  BE:
    image: vulebaolong/img-be_cyber_community:latest
    container_name: con-be_cyber_community
    ports:
      - 3070:3069
    env_file:
      - .env

  DB:
    image: mysql:latest
    container_name: node-52-mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234